services:
  nifi:
    image: apache/nifi:latest
    ports:
      - "8443:8443"
    environment:
      NIFI_WEB_HTTP_PORT: 8443
      SINGLE_USER_CREDENTIALS_USERNAME: admin
      SINGLE_USER_CREDENTIALS_PASSWORD: admin
    volumes:
      - ./tmp:/tmp
      - ./input:/input
      - ./output:/output
