services:
  nifi:
    image: apache/nifi:latest
    ports:
      - "8080:8080"
    environment:
      NIFI_WEB_HTTP_PORT: 8080
    volumes:
      - ./nifi_data:/opt/nifi/nifi-current
      - ./tmp:/nifi-tmp
      - ./input:/input
      - ./output:/output
